apiVersion: v1
kind: Pod
metadata:
  name: model 
spec:
  containers:
  - image: scooter2022/model:1.0
    imagePullPolicy: Always
    name: model
  - image: scooter2022/test:1.1
    name: test
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 60; done;" ]
